--- 
title: "Testing Reticulate"
author: "JW"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(dplyr)
library(readr) 
library(glue) 
library(jsonlite) 

library(reticulate)
# use_condaenv("r-reticulate")
# py_install("pandas")
# py_install("praw")

```



# Python

```{python, echo=FALSE}

import pandas as pd
import praw

reddit = praw.Reddit(
     client_id="CARTER CLIENT ID",
     client_secret="CARTER CLIENT ID",
     user_agent="Rmd.python.postanalysis.edu:v0.1 (by /u/CARTER PUT YOUR OWN SHIT HERE)"
 )


posts = []
ml_subreddit = reddit.subreddit('wallstreebets')
for post in ml_subreddit.hot(limit=250):
    posts.append([post.title, post.score, post.id, post.subreddit, post.url, post.num_comments, post.selftext, post.created])
posts = pd.DataFrame(posts,columns=['title', 'score', 'id', 'subreddit', 'url', 'num_comments', 'body', 'created'])
print(posts)

```




# R


```{r}

df_posts <- py$posts %>%
	dplyr::select(title, score, num_comments) 

title_cols <- glue("word{1:100}")

titles <- df_posts %>%
	dplyr::select(title) %>%
	separate(title, into=title_cols, sep=" ") %>%
	pivot_longer(word1:word100, values_drop_na = TRUE)

sum_titles <- titles %>%
	dplyr::select(value) %>%
	dplyr::group_by(value) %>%
	dplyr::summarise(count=n()) %>%
	dplyr::arrange(desc(count)) %>%
	dplyr::slice(1:10)
sum_titles

```

















